version: "3"
services:
    app:
        build:
          context: ..
          dockerfile: .devcontainer/Dockerfile

        volumes:
          - ../..:/workspaces:cached

        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity

        # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
        network_mode: service:mysqldb
    
    stock:
        image: pythonstock/pythonstock:latest
        container_name: stock
        ports:
            - "8888:8888"
            - "9999:9999"
        volumes:
            - "./data/notebooks:/data/notebooks"
            - "./data/logs:/data/logs"
            - "./jobs:/data/stock/jobs"
            - "./libs:/data/stock/libs"
            - "./web:/data/stock/web"
        environment:
            MYSQL_HOST: mysqldb
            MYSQL_USER: root
            MYSQL_PWD: mysqldb
            MYSQL_DB: stock_data
            LANG: zh_CN.UTF-8
            LC_CTYPE: zh_CN.UTF-8
            PYTHONIOENCODING: utf-8
        links:
            - mysqldb:mysqldb
        restart: always
        
    mysqldb:
        image: mysql:5.7
        container_name: mysqldb
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysqldb
            MYSQL_DATABASE: stock_data
            TZ: Asia/Shanghai
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_general_ci',
            '--max_connections=3000'
        ]
        restart: always

volumes:
  mysql-data:
        
